### ISSUE TITLE
[UX] Displaying Error Message for Missing Note Title

### ISSUE THREAD

**Issue by vaishak10** [brrkrmn/codeandline#2]
## Description
When attempting to create a new note, if the user does not enter a note title, the note is not created and the user is redirected back to the home page. This leads to all the entered data being lost, which results in a poor user experience. Instead, an error message should be displayed near the title input field, indicating that the note title is required to create a note.

### Steps to Reproduce:

	1.	Navigate to the “Create Note” page.
	2.	Fill in all the fields except the “Note Title”.
	3.	Attempt to create the note.

## Expected Behavior
An error message should be displayed near the “Note Title” input field, indicating that the note title is required to create a note. The user should remain on the “Create Note” page with their entered data intact.

## Actual Behavior
The user is redirected back to the home page, and all the entered data is lost.

## Impact

	•	Loss of user data
	•	Frustration due to having to re-enter all data

## Proposed Solution
Display an error message near the “Note" title input field if it is left empty when attempting to create a note. Ensure that the user remains on the “Create Note” page with their entered data preserved.

## Attachments
Screen recording illustrating the issue is available

https://github.com/brrkrmn/codeandline-frontend/assets/52874416/ae2b5aba-9628-405e-a8cd-61f18c93cf1e

**Comment by brrkrmn** [comment]
Hello @vaishak10 👋🏻, thanks for pointing this out. 

With [this change](https://github.com/brrkrmn/codeandline-frontend/commit/45e314b051a6ad8a114885470cc32627aab2a3fd), the problem should be solved. Now submitting the form with empty title will display an error message and not redirect to the homepage.
